---
- hosts: all
  sudo: true
  vars:
    zsh_theme: dpoggi
    zsh_plugins: git github composer grunt sudo supervisor
    apache_port: 8081
    ssh_known_hosts_command: "ssh-keyscan -H -T 10"
    ssh_known_hosts_file: "/home/vagrant/.ssh/known_hosts"
    ssh_known_hosts:
    - moc-files
    - github.com
    - git.moc.net

  handlers:
    - name: reload apache
      service: name=apache2 state=reloaded
    - name: restart apache
      service: name=apache2 state=restarted
    - name: restart php
      service: name=php5-fpm state=restarted
    - name: restart varnish
      service: name=varnish state=restarted
    - name: restart nfs
      service: name=nfs-kernel-server state=restarted
    - name: restart elasticsearch
      service: name=elasticsearch state=restarted
    - name: restart pound
      service: name=pound state=restarted

  tasks:
    #Role common
    - include: tasks/apt.yml
    - include: tasks/dotdeb.yml
    - include: tasks/backports.yml
    - include: tasks/common.yml
    - include: tasks/motd.yml
    - include: tasks/git.yml
    - include: tasks/zsh.yml
    - include: tasks/nfsserver.yml

    #Role Web application server (includes Varnisgh, MySQL etc)
    - include: tasks/phpapachefpm.yml
    - name: install mysql
      apt: name=mysql-server state=present
    - include: tasks/redis.yml
    - include: tasks/memcache.yml
    - include: tasks/varnish.yml
    - name: Make vagrant part of www-data group
      user: name=vagrant group=www-data groups=users,sudo
    - include: tasks/pound.yml


    #Role dev tools
    - include: tasks/compass.yml
    - include: tasks/nodejs.yml
    - include: tasks/grunt.yml
    - include: tasks/bower.yml
    - include: tasks/composer.yml
    - include: tasks/known_hosts.yml
    - include: tasks/gerritcommand.yml

    #Role elastic search (Does java go into common?
    - include: tasks/java.yml
    - include: tasks/elasticsearch.yml

    - include: tasks/rosemary.yml

# Mangler
#
# * Rosemary git
# * [Udsat] Opgradering til Apache 2.4 !!!
# * [DONE] Varnish
# * Stillingtagen til php-fpm brugere (default www-data, skal det hellere være vagrant?)
# * Installere bower (npm install -g bower)
# * [DONE] NFS mounts
# * [DONE] php-fpm instillinger
# * Tomcat + Solr
# * [DONE] Elasticsearch
# * Beanstalkd
# * Supervisor
# * [DONE] zsh med oh-my-zsh
# * Std. pakker (vim, emacs htop etc)
# * [DONE] npm
# * [DONE] grunt
# * [DONE] compass
# * [DONE] git! (I nyere version?)
# * mongo
# * Refactor tasks to roles pattern
# * Mailcatcher [Sæt enten php eller maileragent]
