---

- name: dotdeb | add main repository
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org wheezy all
    - deb-src http://packages.dotdeb.org wheezy all
  tags: dotdeb

- name: dotdeb | add php 5.5 repository
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org wheezy-php55 all
    - deb-src http://packages.dotdeb.org wheezy-php55 all
  tags: dotdeb

- name: dotdeb | install key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg
  tags: dotdeb
