---


- name: Elasticsearch | Add key
  apt_key:
    url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Elasticsearch | Setup elastico repo
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main' update_cache=yes

- name: Elasticsearch | Install Elasticsearch
  apt: name=elasticsearch state=present

- name: Elasticsearch | Start Elasticsearch
  service: name=elasticsearch state=started enabled=yes

- name: Install elasticsearch conf (/etc/elasticsearch/elasticsearch.yml)
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
  notify:
    - restart elasticsearch

## Start elastic search
