---


#- name: download fmysql-apt-config
#  get_url:
#    url: http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
#    dest: /home/{{ ansible_env.USER }}/mysql-apt-config_0.7.3-1_all.deb
#    mode: 0440
#
#- name: Install my_package
#  apt: deb="/home/{{ ansible_env.USER }}/mysql-apt-config_0.7.3-1_all.deb"
#  sudo: true


- name: Download and Install mysql-apt-config
  apt:
    deb: http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb

- name: Update repositories cache and install "mysql-community-server" package
  apt:
    name: mysql-community-server
    update_cache: yes
    force: yes

- name: Set empty password for root
  shell: "mysql mysql -e \"UPDATE mysql.user SET authentication_string = PASSWORD(''), plugin = 'mysql_native_password' WHERE User = 'root' AND Host = 'localhost'; FLUSH PRIVILEGES;\""

- name: Copy mysql.cnf
  copy: dest=/etc/mysql/conf.d/vagrant.mysql.cnf src=mysql.cnf force=no mode=0644
