---

- name: Ensure NFS utilities are installed.
  apt: "name={{ item }} state=installed"
  with_items:
    - nfs-common
    - nfs-kernel-server

- name: Creates directory
  file: path=/home/sites state=directory owner=vagrant group=www-data

- name: Export /home/sites directory
  template:
    src=exports.j2
    dest=/etc/exports owner=root
  notify:
    - restart nfs

