---

- name: install apache
  apt: name='{{ item }}' state=present
  with_items:
    - apache2
    - apache2-mpm-worker
    - libapache2-mod-fastcgi

- name: Enable mod actions in apache
  shell: a2enmod actions creates=/etc/apache2/mods-enabled/actions.load

- name: install PHP and module
  apt: name='{{ item }}' state=present
  with_items:
    - php5-cli
    - php5-fpm
    - php5-gd
    - php5-ldap
    - php5-mysql
    - php5-curl
    - php5-sqlite
    - php5-pgsql
    - php5-imagick
    - php5-mcrypt

- name: Enable fast cgi php handler by default
  template:
    src=fastcgi.j2
    dest=/etc/apache2/mods-enabled/fastcgi_phpfpm.conf
  notify:
    - reload apache

- name: Move Apache to port 8080
  template:
    src=ports.j2
    dest=/etc/apache2/ports.conf owner=root
  notify:
    - reload apache

- name: Update default vhost to port 8080
  template:
    src=default-vhost.j2
    dest=/etc/apache2/sites-available/default
  notify:
    - reload apache

- name: copy default timezone (fpm)
  copy: dest=/etc/php5/fpm/conf.d/timezone.ini content="date.timezone = Europe/Copenhagen"
  notify: restart php

- name: copy default timezone (cli)
  copy: dest=/etc/php5/cli/conf.d/timezone.ini content="date.timezone = Europe/Copenhagen"

- name: Remove default index.html file
  file: path=/var/www/index.html state=absent

- name: Copy default index.php file
  template: src=index.php.j2 dest=/var/www/index.php

- name: start php
  service: name=php5-fpm state=started enabled=yes



