---


- name: Clone Rosemary repo
  git:
    repo=https://github.com/mocdk/Rosemary.git
    dest=/home/vagrant/Rosemary
    update=no
    accept_hostkey=true

- name: Run composer install
  command: composer install chdir=/home/vagrant/Rosemary

- name: Make symlink rosemary command in /usr/local/bin
  file:
    path=/usr/local/bin/rosemary
    mode=0775
    src=/home/vagrant/Rosemary/application.php
    state=link

- cron: name="Create cronjob for rosemary update" special_time=reboot job="cd /home/vagrant/Rosemary; git pull"