---

- name: Copy install-solr-existing-tomcat.sh
  copy: dest=/tmp/install-solr-existing-tomcat.sh src=install-solr-existing-tomcat.sh force=no mode=0755

- name: Running install-solr-existing-tomcat.sh
  command: /tmp/install-solr-existing-tomcat.sh english danish
  args:
    creates: /opt/solr-tomcat


#- name: Download Tika
#  get_url: url=http://archive.apache.org/dist/tika/tika-app-1.4.jar dest=/home/solr/bin/tika-app-1.4.jar mode=0755 owner=vagrant group=www-data

