---

#- name: Create /home/solr directory
#  file: path=/home/solr state=directory owner=vagrant group=www-data

- name: Copy solr home
  copy: dest=/home/solr src=solr/solr-home/ force=no owner=vagrant group=www-data
  notify: restart tomcat

- name: Copy solr.war
  copy: dest=/var/lib/tomcat7/webapps/solr.war src=solr/solr.war force=no
  notify: restart tomcat

- name: Copy solr.xml file
  copy: dest=/var/lib/tomcat7/conf/Catalina/localhost/solr.xml src=solr/solr.xml
  notify: restart tomcat

- name: Copy needed logging files
  copy: dest=/usr/share/tomcat7/lib/ src=solr/libs/
  notify: restart tomcat

- name: Copy tomcat default files
  copy: dest=/etc/default/tomcat7 src=solr/tomcat7_default
  notify: restart tomcat


