---

- name: Instal zsh and theme
  apt: name=zsh

- name: Clone oh-my-zsh repo
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    dest=/home/vagrant/.oh-my-zsh
    update=no

- name: Clone TYPO3 Flow Helper for Oh-my-ZSH
  git:
    repo=hhttps://github.com/sandstorm/oh-my-zsh-flow3-plugin.git
    dest=/home/vagrant/.oh-my-zsh/custom/plugins
    update=no

- name: deploy .zshrc
  template: src=zshrc.j2 dest=/home/vagrant/.zshrc owner=vagrant

- name: Set zsh as default shell
  user: name=vagrant shell=/bin/zsh